# Generated by Django 5.1.1 on 2024-10-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='admin', max_length=100)),
                ('email', models.EmailField(default='admin@kku.ac.th', max_length=100)),
                ('password', models.CharField(default='admin1234', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=17)),
                ('password', models.CharField(max_length=20)),
                ('employee_id', models.CharField(max_length=10)),
            ],
        ),
    ]
