# Generated by Django 5.1.1 on 2024-10-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_admin_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('equipment_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('parcel_id', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('date_borrow', models.DateField(blank=True, help_text='Date when the item was borrowed', null=True)),
                ('date_return', models.DateField(blank=True, help_text='Date when the item is returned', null=True)),
            ],
        ),
    ]
