# Generated by Django 5.1.1 on 2024-10-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_equipment_image'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='equipment',
            constraint=models.UniqueConstraint(fields=('parcel_id',), name='unique_parcel_id'),
        ),
    ]
