# Generated by Django 5.1.1 on 2024-10-14 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_staff_email_alter_staff_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_on', models.DateTimeField(auto_now_add=True)),
                ('returned_on', models.DateTimeField(blank=True, null=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.student')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.equipment')),
            ],
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
