# Generated by Django 5.1.1 on 2024-10-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_borrowing_delete_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='kkumail',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
