# Generated by Django 5.1.1 on 2024-10-14 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_rename_equipment_borrowing_equipment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowing',
            name='borrowed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
